// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['app']['Application']['ClearHistory']();
}

export function GetClipboard() {
  return window['go']['app']['Application']['GetClipboard']();
}

export function GetHistory() {
  return window['go']['app']['Application']['GetHistory']();
}

export function GetLanguages() {
  return window['go']['app']['Application']['GetLanguages']();
}

export function ToggleAlwaysOnTop(arg1) {
  return window['go']['app']['Application']['ToggleAlwaysOnTop'](arg1);
}

export function Translate(arg1) {
  return window['go']['app']['Application']['Translate'](arg1);
}
