// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {interfaces} from '../models';

export function ClearHistory():Promise<void>;

export function GetClipboard():Promise<string>;

export function GetHistory():Promise<Array<interfaces.TranslationDTO>>;

export function GetLanguages():Promise<Array<interfaces.LanguageDTO>>;

export function ToggleAlwaysOnTop(arg1:boolean):Promise<void>;

export function Translate(arg1:interfaces.TranslateRequestDTO):Promise<interfaces.TranslationDTO>;
